#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MYNODERED_DIR="$PROJECT_DIR/mynodered"
FLOWS_FILE="$MYNODERED_DIR/nodered.json"

# --- Verify environment and mynodered/ setup ---
source "$PROJECT_DIR/helper-scripts/check-env.sh"

if [[ ! -d "$MYNODERED_DIR/.git" ]] && [[ ! -f "$MYNODERED_DIR/.git" ]]; then
  echo "mynodered/ is not set up yet. Run init.sh first." >&2
  exit 1
fi

# --- Check for local modifications ---
# If nodered.json has uncommitted changes, only block if those changes differ from
# the live flows. This allows retries after a failed analysis (where the file was
# downloaded but never committed) while still protecting against losing manual edits.
if [[ -f "$FLOWS_FILE" ]] && \
   [[ -n "$(git -C "$MYNODERED_DIR" status --porcelain -- nodered.json)" ]]; then
  if ! "$PROJECT_DIR/helper-scripts/check-nodered-flows-unchanged.sh" "$FLOWS_FILE" 2>/dev/null; then
    echo "mynodered/nodered.json has local modifications that differ from the live flows." >&2
    echo "Please commit or discard them before downloading fresh flows." >&2
    exit 1
  fi
fi

# --- Download latest flows ---
echo "Downloading latest Node-RED flows..."
echo ""
"$PROJECT_DIR/helper-scripts/download-nodered-flows.sh" "$FLOWS_FILE"
echo ""

# --- Check what changed ---
is_new=false
if ! git -C "$MYNODERED_DIR" ls-files --error-unmatch nodered.json &>/dev/null; then
  is_new=true
fi

if [[ "$is_new" == false ]] && git -C "$MYNODERED_DIR" diff --quiet -- nodered.json; then
  echo "No changes since last download."
  exit 0
fi

if [[ "$is_new" == true ]]; then
  echo "Initial flow download complete."
else
  echo "Flows have changed since last download."
fi

echo ""
read -rp "Would you like to analyze the changes? [Y/n] " analyze
analyze="${analyze:-Y}"
if [[ "$analyze" =~ ^[Yy]$ ]]; then
  echo ""
  cd "$PROJECT_DIR"
  claude \
    --allow-dangerously-skip-permissions \
    --allowedTools "Bash(helper-scripts/*)" \
    --allowedTools "Bash(bash helper-scripts/*)" \
    --allowedTools "Bash(mkdir -p mynodered/*)" \
    --allowedTools "Bash(cp mynodered/nodered.json mynodered/nodered-last-analyzed.json)" \
    --allowedTools "Bash(md5 mynodered/nodered.json)" \
    --allowedTools "Bash(git -C mynodered add nodered-last-analyzed.json)" \
    --allowedTools "Write" \
    --allowedTools "Edit" \
    --allowedTools "mcp__home-assistant__get_entity" \
    --allowedTools "mcp__home-assistant__search_entities_tool" \
    --allowedTools "mcp__home-assistant__list_entities" \
    --allowedTools "mcp__home-assistant__get_history" \
    -- "/analyze-flows"
  echo ""
fi

# --- Check if analysis completed ---
ANALYZED_FILE="$MYNODERED_DIR/nodered-last-analyzed.json"
if ! diff -q "$FLOWS_FILE" "$ANALYZED_FILE" &>/dev/null; then
  echo "Analysis did not complete — skipping commit."
  echo "Run this script again to retry."
  exit 0
fi

# --- Commit to submodule ---
git -C "$MYNODERED_DIR" add nodered.json nodered-last-analyzed.json
# Include any doc changes generated by the analysis.
if [[ -d "$MYNODERED_DIR/docs" ]]; then
  git -C "$MYNODERED_DIR" add docs/
fi
git -C "$MYNODERED_DIR" commit -m "Latest changes downloaded from Home Assistant."
echo ""
echo "Committed updated flows to mynodered/."
